import * as React from "react";
import PageLayout from "../components/page-layout";
import Banner from "../components/banner";
import "../index.css";
import {
  Template,
  GetPath,
  GetRedirects,
  TemplateConfig,
  TemplateProps,
  TemplateRenderProps,
  GetHeadConfig,
  HeadConfig,
} from "@yext/pages";
 
 
 export const config: TemplateConfig = {
   name: "index",
 };
 
 
  export const getPath: GetPath<TemplateProps> = ({document}) => {
    return `index.html`;
 };
 
 export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = ({relativePrefixToRoot, path, document}): HeadConfig => {
  return {
    title: "Home Page",
    charset: "UTF-8",
    viewport: "width=device-width, initial-scale=1",
    tags: [
      {
        type: "meta",
        attributes: {
          description: "This site was generated by the Yext SSG",
        },
      },
    ],
  };
};

  const Index: Template<TemplateRenderProps> = ({relativePrefixToRoot, path, document}) => {
  const {
    logo,
    c_primaryColor,
  } = document;

   return (
    <>
        <div className="centered-container">
          <div className="section space-y-10 px-10">
              <h1 className="text-center">Welcome to Garrett's Site!</h1>
              <div className="px-14 space-y-5">
                <p>
                   Partner pages!
                </p>
            </div>
          </div>
        </div>
    </>
   );
 };
 
 export default Index;
 